.PHONY: install validate spec-index-check blueprint-check verify-report test-report-verifier test-evidence-lineage planning-audit gate-check test-go test-go-workspace test-protocol-foundation test-codegen-pipeline test-control-plane-platform test-storage-migrations test-identity-secrets test-publication-contracts test-publication-service test-asset-broker test-registry-core test-registry-api test-registry-recovery verify-registry test-run-lifecycle test-dispatch-ticket test-event-ledger test-direct-proxy-provider test-streaming-resume verify-run-delivery test-worker-service test-go-worker-sdk verify-operations-security test-python-provider test-typescript-consumer test-interop-a2a test-interop-mcp test-interop-ard test-interop-observability test-portable-conformance test-server-conformance test-fault-ha-drivers quickstart-smoke production-reference-smoke verify-resilience manifest-digest

install:
	npm ci

validate: spec-index-check blueprint-check test-report-verifier test-evidence-lineage
	env -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u node_options -u node_path -u npm_config_node_options npm run validate
	env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go test ./...

spec-index-check:
	AROP_CHECK_COMMAND="make spec-index-check" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./internal/tooling/cmd/arop-spec-index-check

blueprint-check:
	AROP_CHECK_COMMAND="make blueprint-check" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./internal/tooling/cmd/arop-blueprint-check

verify-report:
	ALLOW_ANCESTOR="$(ALLOW_ANCESTOR)" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./internal/tooling/cmd/arop-verify-report "$(REPORT)"

test-report-verifier: spec-index-check blueprint-check
	AROP_VERIFY_CURRENT=1 env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go test -count=1 -run TestVerifier ./internal/tooling/report

test-evidence-lineage:
	env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go test -count=1 -run TestEvidenceLineage -v ./internal/tooling/evidence

planning-audit:
	AROP_CHECK_COMMAND="make planning-audit EVIDENCE=<external>" EVIDENCE="$(EVIDENCE)" TRUSTED_KEYS="$(TRUSTED_KEYS)" TRUSTED_CHANNEL_CONFIRMATION="$(TRUSTED_CHANNEL_CONFIRMATION)" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./internal/tooling/cmd/arop-planning-audit

gate-check:
	AROP_CHECK_COMMAND="make gate-check GATE=$(GATE) EVIDENCE=<external> P03_EVIDENCE=<external>" GATE="$(GATE)" EVIDENCE="$(EVIDENCE)" TRUSTED_KEYS="$(TRUSTED_KEYS)" TRUSTED_CHANNEL_CONFIRMATION="$(TRUSTED_CHANNEL_CONFIRMATION)" P03_EVIDENCE="$(P03_EVIDENCE)" P03_TRUSTED_KEYS="$(P03_TRUSTED_KEYS)" P03_TRUSTED_CHANNEL_CONFIRMATION="$(P03_TRUSTED_CHANNEL_CONFIRMATION)" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./internal/tooling/cmd/arop-gate-check

test-go:
	env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go test ./...

test-go-workspace:
	AROP_CHECK_COMMAND="make test-go-workspace" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./internal/tooling/cmd/arop-go-proxy-bootstrap

test-protocol-foundation:
	AROP_CHECK_COMMAND="make test-protocol-foundation" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./conformance/harness/base

test-codegen-pipeline:
	AROP_CHECK_COMMAND="make test-codegen-pipeline" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./conformance/fixtures/codegen-spike/testdata/harness

test-control-plane-platform:
	AROP_CHECK_COMMAND="make test-control-plane-platform" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/app/platform/testdata/harness/main.go"

test-storage-migrations:
	AROP_CHECK_COMMAND="make test-storage-migrations" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/storage/migrate/testdata/engine-versions/harness/main.go"

test-identity-secrets:
	AROP_CHECK_COMMAND="make test-identity-secrets" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/identity/testdata/harness/main.go"

test-publication-contracts:
	AROP_CHECK_COMMAND="make test-publication-contracts" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./conformance/fixtures/contracts/control-plane-publication/testdata/harness

test-publication-service:
	AROP_CHECK_COMMAND="make test-publication-service" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/domain/publication/testdata/harness/main.go"

test-asset-broker:
	AROP_CHECK_COMMAND="make test-asset-broker" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/domain/assets/testdata/harness/main.go"

test-registry-core:
	AROP_CHECK_COMMAND="make test-registry-core" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/domain/registry/testdata/harness/main.go"

test-registry-api:
	AROP_CHECK_COMMAND="make test-registry-api" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/app/registryapi/testdata/harness/main.go"

test-registry-recovery:
	AROP_CHECK_COMMAND="make test-registry-recovery" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/app/registrywatch/testdata/harness/main.go"

verify-registry:
	AROP_CHECK_COMMAND="make verify-registry" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./conformance/fixtures/registry-watch/testdata/verification

test-run-lifecycle:
	AROP_CHECK_COMMAND="make test-run-lifecycle" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/domain/run/testdata/harness/main.go"

test-dispatch-ticket:
	AROP_CHECK_COMMAND="make test-dispatch-ticket" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/domain/dispatch/testdata/harness/main.go"

test-event-ledger:
	AROP_CHECK_COMMAND="make test-event-ledger" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/internal/domain/event/testdata/harness/main.go"

test-direct-proxy-provider:
	AROP_CHECK_COMMAND="make test-direct-proxy-provider" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/conformance/fixtures/provider-reliability/testdata/harness/main.go"

test-streaming-resume:
	AROP_CHECK_COMMAND="make test-streaming-resume" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/conformance/fixtures/streaming/testdata/harness/main.go"

verify-run-delivery:
	AROP_CHECK_COMMAND="make verify-run-delivery" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./conformance/fixtures/streaming/testdata/verification

test-worker-service:
	AROP_CHECK_COMMAND="make test-worker-service" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./conformance/fixtures/worker/testdata/harness

test-go-worker-sdk:
	AROP_CHECK_COMMAND="make test-go-worker-sdk" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./reference/agents/pull-worker/testdata/harness

verify-operations-security:
	AROP_CHECK_COMMAND="make verify-operations-security" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./reference/agents/pull-worker/testdata/verification

test-python-provider:
	AROP_CHECK_COMMAND="make test-python-provider" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PIP_CONFIG_FILE -u PIP_INDEX_URL -u PIP_EXTRA_INDEX_URL -u PIP_TRUSTED_HOST GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./sdk/python/testdata/harness/main.go

test-typescript-consumer:
	AROP_CHECK_COMMAND="make test-typescript-consumer" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./sdk/typescript/testdata/harness/main.go

test-interop-a2a:
	AROP_CHECK_COMMAND="make test-interop-a2a" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./adapters/a2a/testdata/harness/main.go

test-interop-mcp:
	AROP_CHECK_COMMAND="make test-interop-mcp" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./adapters/mcp/testdata/harness/main.go

test-interop-ard:
	AROP_CHECK_COMMAND="make test-interop-ard" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./adapters/ard/testdata/harness/main.go

test-interop-observability:
	AROP_CHECK_COMMAND="make test-interop-observability" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./adapters/observability/testdata/harness/main.go

test-portable-conformance:
	AROP_CHECK_COMMAND="make test-portable-conformance" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./cmd/arop-conformance/testdata/harness/main.go

test-server-conformance:
	AROP_CHECK_COMMAND="make test-server-conformance" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PGPASSWORD -u PGPASSFILE -u PGSERVICE -u PGSERVICEFILE GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run -modfile="$(CURDIR)/go.mod" "$(CURDIR)/reference/control-plane/tests/conformance/harness/main.go"

test-fault-ha-drivers:
	AROP_CHECK_COMMAND="make test-fault-ha-drivers" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PGPASSWORD -u PGPASSFILE -u PGSERVICE -u PGSERVICEFILE GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./conformance/fault-injection/testdata/harness/main.go

quickstart-smoke:
	AROP_CHECK_COMMAND="make quickstart-smoke" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PGPASSWORD -u PGPASSFILE -u PGSERVICE -u PGSERVICEFILE GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./deployments/quickstart/testdata/harness/main.go

production-reference-smoke:
	AROP_CHECK_COMMAND="make production-reference-smoke" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PGPASSWORD -u PGPASSFILE -u PGSERVICE -u PGSERVICEFILE GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./deployments/production-reference/testdata/harness/main.go

verify-resilience:
	AROP_CHECK_COMMAND="make verify-resilience" env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT -u NODE_OPTIONS -u NODE_PATH -u NPM_CONFIG_NODE_OPTIONS -u PYTHONHOME -u PYTHONPATH -u PYTHONSTARTUP -u PYTHONINSPECT -u PYTHONWARNINGS -u PYTHONUSERBASE -u PGHOST -u PGHOSTADDR -u PGPORT -u PGDATABASE -u PGUSER -u PGPASSWORD -u PGSERVICE -u PGSERVICEFILE -u PGPASSFILE -u PGOPTIONS -u PGCONNECT_TIMEOUT -u PGAPPNAME -u PGTARGETSESSIONATTRS -u PGREQUIRESSL -u PGSSLMODE -u PGSSLCERT -u PGSSLKEY -u PGSSLROOTCERT -u PGSSLCRL -u PGSSLCRLDIR -u PGGSSENCMODE -u PGCHANNELBINDING -u PGKRBSRVNAME -u PGSYSCONFDIR -u PGLOCALEDIR -u PGCLIENTENCODING GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./deployments/production-reference/testdata/verification

manifest-digest: export AROP_MANIFEST_FILE := $(value FILE)
manifest-digest:
	@env -u GOFLAGS -u GOENV -u GOWORK -u GOCACHE -u GOCACHEPROG -u GOMODCACHE -u GOTMPDIR -u GOROOT -u GOTOOLCHAIN -u GOEXPERIMENT GOENV=off GOFLAGS=-mod=readonly GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 go run ./cmd/arop manifest digest-env
